name: SkyRealmCore Plugin
description: "§aSkyRealmPE's Core Plugin!"
version: 1.0.0
author: Crafter2012017
api: 3.0.0-ALPHA11
main: SkyCore\Loader\Main
commands:
  feed:
    description: "§bSkyRealm's feed Command :D"
permissions:
  skycore.command.feed:
    description: "Access /feed"
    default: op
 
